Bugfix/assembler memory
EBI-Metagenomics/miassembler pull request #19
Opened 2024-09-16 17:10 UTC by SandyRogers

## PR checklist

This PR improves the retry-with-more-memory logic, by setting `maxRetries` directive to a parameter (default 5) specifically for the spades/megahit assembly modules. The more-memory-with-each-attempt was already present, this just allows those retries to happen.

- [x] This comment contains a description of changes (with reason).
- [x ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/ebi-metagenomics/miassembler/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-09-16 19:41 UTC, mberacochea requested changes
Very cool :+1:

2024-09-16 19:41 UTC, mberacochea commented on nextflow_schema.json
> +                    "default": 5,
5 it's probably too much

2024-09-16 19:41 UTC, mberacochea commented on nextflow.config
> +    max_spades_retries               = 5
I would set this to 3, 5 could cause the whole job to take more than week in some cases (which slurm won't like)

2024-09-17 08:15 UTC, mberacochea approved these changes
:shipit:

2024-09-17 08:31 UTC, KateSakharova approved these changes
perfection!

2024-09-17 10:10 UTC, merged