Fixed regex in modules.config + codon ref genome
EBI-Metagenomics/miassembler pull request #31
Opened 2024-12-17 13:45 UTC by Ge94

Draft PR for numerous bugs to be fixed in miassembler:
- adapted human reference genome name to genome name in codon
- adjusted modules name in modules.config

2025-01-14 11:02 UTC, jmattock5 commented
Solving the following bugs:
- pipeline failed when the assembly, after host cleaning, was empty
- ENA rejecting assemblies being uploaded that contained fewer than 2 contigs
- Scientific notation error when the jgi_summarize_contigs output was being used to calculate depth - due to long contigs who's length was for example 2.60658e+06

I have added a filtering step to short_reads_assembly_qc.nf, after the host cleaning, which counts the number of contigs and only generates cleaned_contigs.fa.gz if the threshold is met - I had to remove the extra metadata generated during this quality check for the rest of the pipeline to run. I've set the default as 2 contigs so this fix solves problem 1&2.

I think there was still an issue with which file was being published in PUBLISH_CLEANED_CONTIGS. It was filtered_contigs which I think meant any non-human host cleaning still wasn't being used. Please check that this logic makes sense in my changes!

I've added another if statement to short_reads_assembly_qc.nf so if no reference is specified it still uses the length and human filtered outputs. Again please check this logic.

The qc_failed_runs csv generated now includes samples that fail the assembly qc check I've added. We could split this into another csv if we wanted this to be separate from the read qc output.

2025-01-17 15:53 UTC, mberacochea requested changes
Thank you, @jmattock5. It looks pretty good to me. I added some nitpicky comments; I've learned that having clear names makes it easier to follow the code, so I've included some suggestions to improve them.

2025-01-17 15:53 UTC, mberacochea commented on subworkflows/local/short_reads_assembly_qc.nf
> +    /*  - Less than 2 contigs                  */
Less that 
```suggestion
    /*  - Less than params.short_reads_contig_threshold (default is 2) contigs                  */
```

2025-01-17 15:53 UTC, mberacochea commented on subworkflows/local/short_reads_assembly_qc.nf
> +    }
I think this version is easier to read, less code and no extra variables (I haven't tested this BTW)
```suggestion
    cleaned_contigs.map { meta, assembly_fasta -> {
           [meta , ["contigs_count": assembly_fasta.countFasta()], assembly_fasta]
            }
        }
        .branch { meta, meta2, assembly_fasta ->
            qc_failed: meta2.contigs_count < params.short_reads_contig_threshold
            qc_passed: meta2.contigs_count >= params.short_reads_contig_threshold
        }
    .set { qc_filtered_assemblies }

    passed_cleaned_contigs = qc_filtered_assemblies.qc_passed.map { meta, _meta2, assembly -> 
            [ meta, assembly ]
    }
```

2025-01-17 15:53 UTC, mberacochea commented on subworkflows/local/short_reads_assembly_qc.nf
> +
```suggestion
```

2025-01-17 15:53 UTC, mberacochea commented on subworkflows/local/short_reads_assembly_qc.nf
> +    if(reference_genome == null) {
```suggestion
    if (reference_genome == null) {
```

2025-01-17 15:53 UTC, mberacochea commented on subworkflows/local/short_reads_assembly_qc.nf
> +    qc_assem_failed = qc_filtered_assemblies.qc_failed // tuple(meta)
```suggestion
    qc_failed_assemblies = qc_filtered_assemblies.qc_failed.map { meta, assembly -> [meta + ["too_few_contigs": true], assembly } // tuple(meta)
```

2025-01-17 15:53 UTC, mberacochea commented on workflows/miassembler.nf
> +            error("Unexpected. meta: ${meta}")
I think this error needs to go outside the if

2025-01-17 15:53 UTC, mberacochea commented on workflows/miassembler.nf
> +    def short_reads_qc_failed_entries = SHORT_READS_ASSEMBLER.out.qc_all_failed.map {
```suggestion
    def short_reads_qc_failed_entries = SHORT_READS_ASSEMBLER.out.qc_failed_assemblies.map { 
```

2025-01-17 15:53 UTC, mberacochea commented on workflows/short_reads_assembler.nf
> +    qc_all_failed = qc_reads_failed.concat(SHORT_READS_ASSEMBLY_QC.out.qc_assem_failed)
```suggestion
    qc_all_failed = qc_reads_failed.concat(SHORT_READS_ASSEMBLY_QC.out.qc_failed_assemblies)
```

2025-01-17 15:53 UTC, mberacochea commented on workflows/short_reads_assembler.nf
> +    qc_all_failed = qc_reads_failed.concat(SHORT_READS_ASSEMBLY_QC.out.qc_assem_failed)
Mayb I would rename to `qc_failed` instead of `qc_failed_all`

2025-01-17 15:53 UTC, mberacochea commented on subworkflows/local/short_reads_assembly_qc.nf
> +    if(reference_genome == null) {
I think it would be better to move this to the top and remove this extra if.
```
filtered_contigs = SEQKIT_SEQ.out.fastx
// The cleaned contigs are those that have been filtered, but they will be further cleaned if a reference genome is set.
cleaned_contigs = filtered_contigs
```

2025-01-22 09:06 UTC, jmattock5 commented on subworkflows/local/short_reads_assembly_qc.nf
> +    if(reference_genome == null) {
I got rid of this if statement but moved this to be between human+phiX cleaning and host cleaning so it'd catch samples where host cleaning isn't done:

   ```
 // The cleaned contigs are those that have been filtered, but they will be further cleaned if a reference genome is set.
    cleaned_contigs = filtered_contigs
```

2025-01-22 09:10 UTC, jmattock5 commented on bin/calculate_assembly_coverage.py
> +            if not contig_length_str.is_integer():
Using isnumeric gives this error:
`AttributeError: 'float' object has no attribute 'is_numeric'`
Using is_integer catches any letters that shouldn't be in there but lets python deal with the scientific notation appropriately

2025-01-22 09:12 UTC, jmattock5 commented
Thanks for your comments! I've made all the changes you suggested but for two, please look at my comments for justification

2025-01-23 12:18 UTC, mberacochea approved these changes
Nice work :medal_sports: @jmattock5

2025-01-23 13:24 UTC, merged